#!/bin/bash

SCRIPT_PATH=$(dirname "$0")
source "${SCRIPT_PATH}/../.env"
export CHORDS_GENIUS_ELASTICSEARCH_PORT="${ELASTICSEARCH_PORT}"

docker-compose --log-level DEBUG --verbose -f ${SCRIPT_PATH}/docker-compose.yml up
